<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path3</name>
   <tag></tag>
   <elementGuidId>d4de517f-e777-477e-9589-890ff718fa55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>67afd250-54cb-402d-af58-79a5b6dd24bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#7cb5ec</value>
      <webElementGuid>20843ffb-4de3-418b-976f-2570e02209d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 356 229.07992104420424 A 5.999921044203816 5.999921044203816 0 1 1 356.00599992004425 229.07991804424398 Z</value>
      <webElementGuid>ddf68cbc-fe49-4a5a-bfd1-41f8b59f2bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>e0693b49-0322-4dc9-8541-4ed3c6fd0614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0.9999605221019081</value>
      <webElementGuid>259cd0dd-933b-4bfc-a676-e092e7793289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbd92059-e643-435f-9a68-371943ccc7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point highcharts-color-0</value>
      <webElementGuid>5afc47a2-9a66-4802-a01d-b8e9c070b56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>60c8a03a-9d26-40d7-8c8f-69d3de89e933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d20d7ef0-65b9-4a09-86ba-163867ca7808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Development, 60,000. Allocated Budget.</value>
      <webElementGuid>b3b4a89c-2b8a-4a5c-89a7-7d83fc4c4679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-d50dff2-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-markers highcharts-series-0 highcharts-line-series highcharts-color-0 highcharts-tracker&quot;]/path[@class=&quot;highcharts-point highcharts-color-0&quot;]</value>
      <webElementGuid>cef99cec-3e5a-4f74-bc30-b852dc906fa9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
