<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path2</name>
   <tag></tag>
   <elementGuidId>8b846ba9-6034-4931-90a8-00908f9a2644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.highcharts-point.highcharts-color-0.highcharts-point-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>8fb7ad10-b706-42e3-9206-0506bb17b541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#7cb5ec</value>
      <webElementGuid>d2048b46-893e-44a6-9d76-82e12c38ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 236 190.3226666666664 A 6 6 0 1 1 236.005999999 190.32266366666667 Z</value>
      <webElementGuid>3d434fb1-d312-4ba4-9003-482279953af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>b18e0e51-28ec-4e70-8bc9-589b4ea51ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>48734dfc-c821-4ef9-a62b-e9f10b51ddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a442a8bd-2c67-4aca-88e4-7b9f7464531d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point highcharts-color-0 highcharts-point-hover</value>
      <webElementGuid>49a93d6e-2351-4417-b17b-8c5c020fa887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>156ebd4f-7648-4c20-81ee-3b09ecb6b885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93dfceb2-356f-43fc-956d-3d976df6c082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Information Technology, 17,000. Allocated Budget.</value>
      <webElementGuid>b2134daf-2855-43a7-8af1-084eeaa1e228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-d50dff2-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-markers highcharts-series-0 highcharts-line-series highcharts-color-0 highcharts-tracker&quot;]/path[@class=&quot;highcharts-point highcharts-color-0 highcharts-point-hover&quot;]</value>
      <webElementGuid>896d7f02-3a34-4585-80d7-a28a74834331</webElementGuid>
   </webElementProperties>
</WebElementEntity>
